# Generated by Django 4.1.9 on 2023-05-24 02:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_movie_director"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieActors",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                ("actor", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.actor")),
                ("movie", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="movies.movie")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(through="movies.MovieActors", to="movies.actor"),
        ),
    ]
